# Tiling
general {
	gaps_in = 5
	gaps_out = 10
	border_size = 2
	col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
	col.inactive_border = rgba(595959aa)
	layout = dwindle
}

xwayland {
  force_zero_scaling = true
}

binds {
    scroll_event_delay = 300
}

# Environment Variables
env = STEAM_FORCE_DESKTOPUI_SCALING,2#
env = GDK_SCALE,1
env = LOGIND_RENDER_NODE,/dev/dri/renderD128
env = WLR_DRM_DEVICES,/dev/dri/card0
env = NVD_BACKEND,direct
env = GTK_THEME,Adwaita-dark
env = QT_QPA_PLATFORMTHEME,qt6ct

decoration {
    blur {
        enabled = true
        size = 8
        passes = 2
        ignore_opacity = true # This is critical for transparency to work correctly
    }
}
