# Core Componants
#exec-once = waybar
#exec-once = /usr/lib/polkit-kde-authentication-agent-2
#exec-once = systemctl start tailscaled & tailscale up
#exec-once = awww-daemon
#exec-once = ~/scripts/random_wall.sh & caelestia wallpaper -r
#exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#exec-once = nm-applet --indicator
#exec-once = easyeffects --gapplication-service
#exec-once = hyperidle
#exec-once = usbmuxd
#exec-once = ~/.config/hypr/scripts/darkmode.sh

#exec-once = qs -c active

exec-once = noctalia-shell
exec-once = hyprctl setcursor Bibata-Modern-Classic 24

























